### PR TITLE
refactor: update module/project to crossplane-contrib/provider-upjet-github

### PR DESCRIPTION
**Pull request by jbw976**
### Description of your changes

This repository has been generously contributed from its previous source location in `coopnorge/provider-github` to this new home in `crossplane-contrib/provider-upjet-github`. Thank you @AtzeDeVries and team for the awesome work on this provider and the willingness to share it even more openly with the Crossplane community!

See https://github.com/crossplane/crossplane/discussions/5435 for background context.

This PR updates all of the project module/import/build paths to point to this new source location. This could be a breaking change if other projects outside of this repo were importing them directly for source code usage in their repos, but I doubt that was being done. We took a similar approach recently with https://github.com/crossplane-contrib/provider-upjet-mysql/pull/9. 

Note that the CRD API groups aren't updated in this PR, so when folks already using this provider upgrade to the new published location under `crossplane-contrib`, they shouldn't be impacted at all.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

We will be relying heavily on a successful CI run of unit tests and end to end tests for this provider. Let me know if there's other additional testing we should perform.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by AtzeDeVries — APPROVED** [review]
LGTM, thanks!

**Comment by jbw976** [comment]
Awesome @AtzeDeVries this PR is passing all checks! I've created the new repo on `xpkg.upbound.io` with a robot account and updated the secrets that CI will use. I'm hoping after we merge this into main that publishing will work for us successfully 😉

**Comment by AtzeDeVries** [comment]
Awesome!

**Comment by jbw976** [comment]
The provider repo has been set to public in `xpkg.upbound.io`, so the next official release with a release semver will be indexed and publicly displayed in the marketplace!

@AtzeDeVries feel free to cut the next release at your leisure. If there are any issues with it showing up on https://marketplace.upbound.io/providers/crossplane-contrib/provider-upjet-github after a release, please let me know! That link will be a 404 until a release is completed, then it should work.

Also @AtzeDeVries you are admin on this repo, so please add other maintainers and give them permissions if there were any others not yet captured in https://github.com/crossplane-contrib/provider-upjet-github/blob/main/OWNERS.md.

Let me know if I can be of any further help 🙇‍♂️

**Pull request merged**
