### PR TITLE
feat: Add RepositoryCollaborator resource

### LINKED ISSUE #104: Repository Collaborators (Request for Addition)
Hi. I'm trying to utilise this package but it's missing the Repository Collaborators which I need to make use of.

See: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_collaborator

Unfortunately I'm not a Go developer, otherwise I'd raise a PR. It sounds easy enough but I wouldn't be confident that I'd cover off what was needed with the test.

Would anybody be able to assist?

Thank you

### PR DESCRIPTION
**Pull request by asafhm**
### Description of your changes

Fixes #104 

Adds the `RepositoryCollaborator` resource.

### CODE REVIEW

**Comment by im6h** [comment]
@asafhm Your commit is great, so you can sign-off it with ssh key. The team will verify you PR.

**Comment by asafhm** [comment]
Thank you! 😁 Signed it.

**Comment by steveizzle** [comment]
Why is the bot unhappy? Seems to be signed now?

**Comment by asafhm** [comment]
@steveizzle Sorry my bad. Fixed it now.

**Comment by asafhm** [comment]
Any chance to get this looked at?

**Comment by steveizzle** [comment]
please..?

**Comment by AtzeDeVries** [comment]
@asafhm Will get back to this. The CI runs are not triggered so that needs some investigation.

**Review by AtzeDeVries — APPROVED** [review]

**Comment by jamescooke-xyz** [comment]
Thank you all

**Pull request merged**
